
let shopItemsData = [
    {
        id: "jfhgbvnscs",
        name: "Aquamarine: The Sea-Inspired Gemstone",
        price: 6950,
        desc: "When you think of aquamarine, the first thing that comes to mind is probably its stunning blue-green color, reminiscent of the sea. But there’s more to aquamarine, the sea-inspired gemstone, than just its appearance. Aquamarine is a member of the beryl family, which also includes the popular gemstones emerald and morganite.",    //         "category": "jewelery",",
        img: "/monkeybusiness.com/imgs/gems/aquamarine.png",
    },
    {
        id: "ioytrhndcv",
        name: "Ruby: The King of Gemstones",
        price: 2500,
        desc: "Many medieval Europeans wore rubies to guarantee health, wealth, wisdom, and success in love. Desire for ruby is just as great today as it always has been. As a symbol of passion, ruby makes an ideal romantic gift. Consumers are drawn to the lush color because it also signifies wealth and success.",
        img: "/monkeybusiness.com/imgs/gems/ruby.png",
    },
    {
        id: "wuefbncxbsn",
        name: "Emerald: The Gemstone of Love",
        price: 3500,
        desc: "Emerald symbolism encompasses not only royalty but also wit, eloquence, and foresight.People believed emeralds could confer riches, power, and eloquence if worn as talismans. Purportedly, these gems also strengthened memory and sharpened wits. Its most valuable power was perhaps bestowing the ability to predict future events.",
        img: "/monkeybusiness.com/imgs/gems/emerald.png",
    },
    {
        id: "thyfhcbcv",
        name: "Moonstone: The Stone of New Beginnings",
        price: 1500,
        desc: "Wisdom and Fertility. In New Age beliefs, moonstone symbolizes the feminine, intuition, new beginnings, and inner wisdom. Because of the association with the moon and lunar cycles, in crystal healing, it is said to promote healthy menstrual cycles in women and aid fertility.",
        img: "/monkeybusiness.com/imgs/gems/moonstone.png",
    },
    {
        id: "thiecbawdjksadjk",
        name: "Diamond: One and Only",
        price: 10099,
        desc: "Diamonds are associated with strength, love and health. As we have uncovered, throughout history, diamonds have been worn by leaders or power figures to symbolise strength and invincibility. Diamonds have also been associated with good health and represent long life and good heart health.",
        img: "/monkeybusiness.com/imgs/gems/diamond.png",
    },
    {
        id: "iuertrywebncdjksadjk",
        name: "Amethyst: The Stone of Sobriety",
        price: 2500,
        desc: "The gem's purple colors represented purity of spirit. Its purplish and reddish hues represented the chastening and purifying effects of suffering. Some believed the colors alluded to the wounds and suffering of Christ. Thus, amethysts were used to aid the healing of wounds.",
        img: "/monkeybusiness.com/imgs/gems/Amethyst.png",
    },
    {
        id: "thierytbvcbvzdhadjk",
        name: "Blue Sapphire: The Gemstone of Truth",
        price: 5498,
        desc: "Blue sapphire is said to bring luck, loyalty, happiness and love. Its symbolism and durability make it ideal for engagement rings.",
        img: "/monkeybusiness.com/imgs/gems/BlueSapphire.png",
    },
    {
        id: "trfoiwfcnbcawdjksadjk",
        name: "Lapis Lazuli:Stone of friendship",
        price: 100,
        desc: "Today, some people associate lapis lazuli with wisdom, love, and healing and claim it nurtures and promotes psychic ability.",
        img: "/monkeybusiness.com/imgs/gems/LapisLazuli.png",
    },
    {
        id: "cbvxbcvsceldk",
        name: "Onyx: The Gemstone of Protection",
        price: 25,
        desc: "In fact, onyx symbolism is replete with connections to bad luck. In Arabic, black onyx is known as el jaza, which means 'sadness.' A manuscript from 1875 notes that in China, slaves and menial servants mined onyx. Nobody would willingly touch or own this gem for fear of bad dreams, misfortune, and loss of energy.",
        img: "/monkeybusiness.com/imgs/gems/Onyx.png",
    },
    {
        id: "oiopijmjkhuihb",
        name: "Peridot: The Gemstone of the Sun",
        price: 3245,
        desc: "Some believe it is derived from the Arabic faridat, meaning “gem,” or from the Greek word, peridona, which means “give in abundance.” Given its resemblance to the color of money, peridot has often been associated with prosperity and good fortune.",
        img: "/monkeybusiness.com/imgs/gems/Peridot.png",
    },
    {
        id: "oiopijewyiohbjhib",
        name: "Quartz: Icy cold",
        price: 75,
        desc: "Quartz enhances spiritual growth, spirituality and wisdom. Because it clarifies thought processes and emotions, it can increase inspiration and creativity. It can also help with concentration, studying and retaining what one learns.",
        img: "/monkeybusiness.com/imgs/gems/Quartz.png",
    },
    {
        id: "rtytytuyuytyytbvncv",
        name: "Tuquoise: The Gemstone of the Sky",
        price: 3000,
        desc: "Turquoise is a popular gemstone that has long been prized in many cultures. It's said to bring luck, peace, and protection, and it's also one of the birthstones associated with December.",
        img: "/monkeybusiness.com/imgs/gems/Turquoise.png",
    },
];